language: java
script: ./mvnw deploy
install: echo 'installing'
env:
  global:
  - ARTIFACTORY_USERNAME=admin
  secure: SOp5bhlhmNoJvpiSdAcT+cscqHUSKzTtynfSTgVkU9ysHJeI4RynWLqvEQQr6/YgNjlYSaOdd6umsHPgdH8FiUficonZVUvf1XqmhUW73jWVlu9yREJ47E+ucplb2zeZ9AGbFEQwCC4ntFGRVkxFQ6f9vjrz4RHIdFNhDVp79sjWVJspX0FtplS77yS9EfGYGLE+pVwsqESaaxUYil9KwLlYOz9QehQoVfuygGXGZwzrYHc76jUzy2EU4/g2+Q7h4iT77+oVHsWDKyFHF5HleB1UaU9PXNzujNF8bD3X36WVp34TRnSpqVA+rdcxp75elvKU9m/bSt/6stMSvCbHD7uD/JLS6/BhvQIx+7YjgSwAIjrPTkbp1Jy+NzwaMJ3X7VAO1Kw/74tCDFjl3hzSniVccyaQbiQQnYkiI9I3i/AZHP9iKmb8blOOq7WK7u6dzCAgwedvTXl5QiJBX0f+GDtAchsHR7rZOr6ZTdZXNto8fZGOlRkQU3cp5ISRf1E98/lZsmrsDxLBKvPZAqy9oqdwtUKr5IJUa1Q02joBi3TwMqdgj9lX3ogitstmjHUy4WJhHVmuDKCagCkTdh3z+TnsrkinDzrkYXP/UE5GA9IHGVuejFMMbGmJ3ESUjQF5+ncf+d8R4dB9r/tDVh2rJygGSQ6iQNVrt9NNJuVDOdk=
jdk:
  - openjdk8